package com.fox.item.dao.template.model;

import com.seedeer.domain.BaseDomain;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table db_ebaysite
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class EbaySite extends BaseDomain {
    /**
     * 
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * 英文名称
     *
     * @mbg.generated
     */
    private String name;

    /**
     * 中文名称
     *
     * @mbg.generated
     */
    private String namecn;

    /**
     * 站点缩写
     *
     * @mbg.generated
     */
    private String abbreviation;

    /**
     * 货币类型["CAD","USD"]
     *
     * @mbg.generated
     */
    private String currency;

    /**
     * 拍卖启始价格
     *
     * @mbg.generated
     */
    private Double startprice;

    /**
     * 一口价的最低价格
     *
     * @mbg.generated
     */
    private Double buyitnowprice;

    /**
     * 计量单位信息
     *
     * @mbg.generated
     */
    private String unitdetail;

    /**
     * 该站点更新类目时间
     *
     * @mbg.generated
     */
    private Date updatecategorytime;

    /**
     * 运送地区
     *
     * @mbg.generated
     */
    private String shippinglocation;

    /**
     * 付款方式
     *
     * @mbg.generated
     */
    private String paymentoption;

    /**
     * Tax税收区域
     *
     * @mbg.generated
     */
    private String salestaxstate;

    /**
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     *
     * @mbg.generated
     */
    public String getNamecn() {
        return namecn;
    }

    /**
     *
     * @mbg.generated
     */
    public void setNamecn(String namecn) {
        this.namecn = namecn == null ? null : namecn.trim();
    }

    /**
     *
     * @mbg.generated
     */
    public String getAbbreviation() {
        return abbreviation;
    }

    /**
     *
     * @mbg.generated
     */
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation == null ? null : abbreviation.trim();
    }

    /**
     *
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     *
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     *
     * @mbg.generated
     */
    public Double getStartprice() {
        return startprice;
    }

    /**
     *
     * @mbg.generated
     */
    public void setStartprice(Double startprice) {
        this.startprice = startprice;
    }

    /**
     *
     * @mbg.generated
     */
    public Double getBuyitnowprice() {
        return buyitnowprice;
    }

    /**
     *
     * @mbg.generated
     */
    public void setBuyitnowprice(Double buyitnowprice) {
        this.buyitnowprice = buyitnowprice;
    }

    /**
     *
     * @mbg.generated
     */
    public String getUnitdetail() {
        return unitdetail;
    }

    /**
     *
     * @mbg.generated
     */
    public void setUnitdetail(String unitdetail) {
        this.unitdetail = unitdetail == null ? null : unitdetail.trim();
    }

    /**
     *
     * @mbg.generated
     */
    public Date getUpdatecategorytime() {
        return updatecategorytime;
    }

    /**
     *
     * @mbg.generated
     */
    public void setUpdatecategorytime(Date updatecategorytime) {
        this.updatecategorytime = updatecategorytime;
    }

    /**
     *
     * @mbg.generated
     */
    public String getShippinglocation() {
        return shippinglocation;
    }

    /**
     *
     * @mbg.generated
     */
    public void setShippinglocation(String shippinglocation) {
        this.shippinglocation = shippinglocation == null ? null : shippinglocation.trim();
    }

    /**
     *
     * @mbg.generated
     */
    public String getPaymentoption() {
        return paymentoption;
    }

    /**
     *
     * @mbg.generated
     */
    public void setPaymentoption(String paymentoption) {
        this.paymentoption = paymentoption == null ? null : paymentoption.trim();
    }

    /**
     *
     * @mbg.generated
     */
    public String getSalestaxstate() {
        return salestaxstate;
    }

    /**
     *
     * @mbg.generated
     */
    public void setSalestaxstate(String salestaxstate) {
        this.salestaxstate = salestaxstate == null ? null : salestaxstate.trim();
    }

    /**
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", namecn=").append(namecn);
        sb.append(", abbreviation=").append(abbreviation);
        sb.append(", currency=").append(currency);
        sb.append(", startprice=").append(startprice);
        sb.append(", buyitnowprice=").append(buyitnowprice);
        sb.append(", unitdetail=").append(unitdetail);
        sb.append(", updatecategorytime=").append(updatecategorytime);
        sb.append(", shippinglocation=").append(shippinglocation);
        sb.append(", paymentoption=").append(paymentoption);
        sb.append(", salestaxstate=").append(salestaxstate);
        sb.append("]");
        return sb.toString();
    }
}